version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: gestao_vagas_postgres
    environment:
      POSTGRES_DB: gestao_vagas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gestao_vagas_network

  prometheus:
    image: prom/prometheus:latest
    container_name: gestao_vagas_prometheus
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: gestao_vagas_grafana
    network_mode: host
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:

networks:
  gestao_vagas_network:
    driver: bridge
