spring.datasource.url=jdbc:h2:mem:gestao_vagas_test;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

security.token.secret = @GESTAO_VAGAS_SECRET@123#
security.token.secret.candidate = @GESTAO_VAGAS_SECRET_CANDIDATE@123#
