spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_vagas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.application.name=gestao_vagas
spring.jpa.hibernate.ddl-auto=update

security.token.secret = @GESTAO_VAGAS_SECRET@123#
security.token.secret.candidate = @GESTAO_VAGAS_SECRET_CANDIDATE@123#
